#!/bin/sh

openssl s_client -debug -connect localhost:11029 \
	-cert certs/server.pem \
	-key certs/server.key \
	-CAfile certs/ca.pem \
	-tls1_3 \
	-groups P-256:X25519 \
	-sigalgs RSA+SHA512:ECDSA+SHA256 \
	-client_sigalgs rsa_pkcs1_sha384